### ISSUE TITLE
[Bug] Jumping on Enemies  

### ISSUE THREAD

**Issue by taradinreinwald** [Taiga74164/Goofland#9]
**Describe the Bug**

 Whenever the player encounters enemies, certain glitches occur When the player jumps on enemies, they can do so with full health and one health, jumping on the enemy causes them to fly up in the air. Upon jumping on an enemy with full health, the player is sent flying up in the air at a rapid pace. The camera struggles to capture the player's movement and often loses track of their position.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any enemies I went to the duck 
2. jump on the enemies 
3. press jump again

**Expected Behavior**
What is expected when jumping on enemies is to die or lose a heart

**Screenshots/Videos**

https://github.com/Taiga74164/Goofland/assets/133139706/7f7a5032-1ae3-4c47-815b-0458adbffed4

![Jump_InAir_Picture](https://github.com/Taiga74164/Goofland/assets/133139706/f14de960-2317-4b95-9320-57c04cbeb722)

**Comment by Taiga74164** [comment]
fixed https://github.com/Taiga74164/Goofland/commit/97c6fbecb7730559700cc1c67cebe1a9344624ae
